version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    env_file: ./.env
    ports:
      - "3306"
    networks:
      - webnet
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    env_file: ./.env
    depends_on:
      - mariadb
    container_name: wordpress-container
    ports:
      - "9000:9000"
    networks:
      - webnet
    restart: on-failure

  nginx:
    build: ./requirements/nginx
    env_file: ./.env
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - webnet
    restart: on-failure

networks:
  webnet:
    name: webnet
    driver: bridge
