services:
  mariadb:
    container_name: mariadb-cont
    image: mariadb
    build: ./requirements/mariadb
    env_file: ./.env
    ports:
      - "3306"
    networks:
      - docker-network
    volumes:
      - mariadb-vol:/var/lib/mysql/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 40s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    
  wordpress:
    container_name: wordpress-cont
    image: wordpress
    build: ./requirements/wordpress
    env_file: ./.env
    networks:
      - docker-network
    expose:
      - "9000"
    volumes:
      - wordpress-vol:/var/www/html/
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true

  nginx:
    depends_on:
      - wordpress
    container_name: nginx-cont
    image: nginx
    build: ./requirements/nginx
    env_file: ./.env
    networks:
      - docker-network
    ports: 
      - "443:443"
    volumes:
      - wordpress-vol:/var/www/html/
    restart: unless-stopped

volumes:
  mariadb-vol:
    driver: local
    driver_opts:
      type: none
      device: "/home/parallels/data/mariadb"
      o: 'bind'

  wordpress-vol:
    driver: local
    driver_opts:
      type: none
      device: "/home/parallels/data/wordpress"
      o: 'bind'

networks:
  docker-network:
    name: docker-network